export const FIRE_EMPLOYEE = 'FIRE_EMPLOYEE'
export const INCREASE_SALARY = 'INCREASE_SALARY'
export const RESET_CHANGES = 'RESET_CHANGES'

export const CREATE_PLAN = 'CREATE_PLAN'
export const SUBMIT_PLAN = 'SUBMIT_PLAN'
export const DELETE_PLAN = 'DELETE_PLAN'
export const SELECT_PLAN = 'SELECT_PLAN'

export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST'
export const FETCH_EMPLOYEES_TOTAL = 'FETCH_EMPLOYEES_TOTAL'
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS'
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE'
